# Generated by Django 2.1.4 on 2019-02-17 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190217_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 10, 4, 44, 126802, tzinfo=utc)),
        ),
    ]
